### ISSUE TITLE
__debugbreak() freezing

### ISSUE THREAD

**Issue by JoeSwansons** [jonomango/hv#10]
I have tried using all sorts of debugging in vmexit and it keeps freezing me, dbgprint, dbgbreak etc

P.S: the irql level is at DISPATCH_LEVEL as recommended by msdn and then restored after sending the dbgprint

is there any sort of vmcs setting that I need to be aware of?

I thought it could be because of the custom idt table, any thoughts?

**Comment by jonomango** [comment]
Yep, it is freezing because of the custom IDT. [This](https://github.com/jonomango/hv/blob/main/hv/vcpu.cpp#L297) is getting called everytime `__debugbreak()` is called in root-mode. I'll be adding a logging system soon and I might add a way to temporarily store/restore the guest context so you can call guest functions from root-mode (even though this is incredibly unsafe and prone to crashes).

**Comment by JoeSwansons** [comment]
Do you know the correct way of handling such an instruction call in the idt?

**Comment by jonomango** [comment]
> Do you know the correct way of handling such an instruction call in the idt?

There is no "correct" way. This is one of the reasons why hypervisor development is so annoying and difficult. Debugging issues that occur in root-mode becomes a nightmare since there is no infrastructure to support it.
