### ISSUE TITLE
Wrong CR3

### ISSUE THREAD

**Issue by badr-tn** [jonomango/hv#18]
Since EAC has started modifying the CR3 value to some wrong value reading physical memory is no longer possible without accessing or finding the original CR3 value so is there a way to find it? Or do I have to just read virtual memory?

thanks :)

**Comment by jonomango** [comment]
Well, reading physical memory doesn't need the CR3 register _(this is a half-lie)_, since the whole point of that register is for translating virtual addresses to physical addresses. Your best bet is just temporarily hooking the game at a known point where it will have a valid CR3 and storing that somewhere.

**Comment by badr-tn** [comment]
That's too complicated for me now I'll just read virtual memory with syscalls thanks 👍🏻
