### ISSUE TITLE
Vlang

### ISSUE THREAD

**Issue by ddkwork** [jonomango/hv#2]
Can you translate this project to vlang?or rust or golang

**Comment by jonomango** [comment]
Probably not. I don't think that it's a good idea to translate this project to golang (or even possible for that matter) since from what I've heard, golang is a pretty high-level language that includes a garbage collector. Not very ideal for systems programming. I've never even heard about vlang before, so I can't really comment on that. Translating to rust is much more viable (there are a few hypervisors written in rust already, such as [rustyvisor](https://github.com/iankronquist/rustyvisor)) but I'm personally not a huge fan of the language so I won't be doing that either.

I'm open to helping out if you plan on doing it yourself, but I don't really see the purpose of translating the entire project to another language. Hypercalls can already be executed from pretty much any language that lets you emit assembly, so if you just wanted to *use* the hypervisor in your language of choice, it shouldn't be too difficult.
