### ISSUE TITLE
Blue screen

### ISSUE THREAD

**Issue by Lexsolena** [jonomango/hv#3]
It eşther stucks when mapping or blue screen

**Comment by jonomango** [comment]
@Lexsolena Hi,

Can you provide some more information about the crash? For example: 
* How are you mapping the driver? Are you manual mapping it?
* What Windows version have you tested on?
* If you BSOD, what is the error code? Can you provide the crash dump?

Make sure to use the latest commit, since the previous one had a very serious bug. I won't be home for a few days, but I'll try to look into your issue when I get back (you'll have to give me some more information though 😄).

**Comment by jonomango** [comment]
Closed due to inactivity.
