### ISSUE TITLE
Question about write_virt_mem()

### ISSUE THREAD

**Issue by untyper** [jonomango/hv#31]
Is `write_virt_mem()` able to write to read-only memory in usermode processes, specifically protected pages containing import address tables (IAT)? What about read-only memory in the kernel space?

If so, how does it achieve this? Does it temporarily disable the `CR0.write_protect` bit? Or is there some other mechanism in play?
If not, how would I go about implementing a custom hypercall that does this?

**Comment by jonomango** [comment]
> Is write_virt_mem() able to write to read-only memory in guest usermode processes, specifically protected pages containing import address tables (IAT)? What about read-only memory in the guest kernel space?
> 
> If so, how does it achieve this? Does it temporarily disable the CR0.write_protect bit? Or is there some other mechanism in play?
If not, how would I go about implementing a custom hypercall that does this?

`write_virt_mem()` is able to write to read-only memory because in the host page tables, they are set as read-write-executable (https://github.com/jonomango/hv/blob/main/hv/page-tables.cpp#L8-L53). All of physical memory is mapped into the host hypervisor's address space, so there is nothing that we're not able to write to.

> I was reading the source of [ept.h](https://github.com/jonomango/hv/blob/86ca9f50238c65b75ef04fdec1f6c45d8e98fdbf/hv/ept.h) and noticed that [ept_free_page_count](https://github.com/jonomango/hv/blob/86ca9f50238c65b75ef04fdec1f6c45d8e98fdbf/hv/ept.h#L11) was set to 100. Does this mean that only 100 pages of the target address space can be EPT switched on access violation? Is there a set limit for it in the Intel standard somewhere?

`ept_free_page_count` is just an arbitrary number. It is the amount of pages in the pool of memory that we allocate beforehand. Feel free to increase/decrease it however you want.

> What if I wanna allocate a range of pages to let's say manually map a DLL into a guests usermode process, can I then take an arbitrary amount of continuous pages matching the size of my DLL anywhere within the guests process and use EPT switching ([install_ept_hook()](https://github.com/jonomango/hv/blob/86ca9f50238c65b75ef04fdec1f6c45d8e98fdbf/um/hv.h#L245)) on said pages to avoid allocating memory with f.ex. VirtualAlloc?

That won't work. EPT hooking isn't really related to allocating memory at all.

> And lastly what's the difference between [hide_physical_page()](https://github.com/jonomango/hv/blob/86ca9f50238c65b75ef04fdec1f6c45d8e98fdbf/um/hv.h#L284) and install_ept_hook() in practice?

They are completely different. Pages that are hidden with `hide_physical_page()` are not accessible to the guest at all. Reading/writing to those pages will just produce junk. Only the hypervisor has access to those pages. `install_ept_hook()` on the other hand, is about creating two separate views for the same physical page. One view is used whenever the guest *reads/writes* memory, and the other view is used when the guest *executes* that memory. This way, you can modify what gets executed while still appearing as if nothing was modified and circumventing integrity checks.
