### ISSUE TITLE
Why Host_CR3 not set __readcr3()

### ISSUE THREAD

**Issue by 1034063174** [jonomango/hv#39]
hi，
I'm learning about vt and trying to understand what each line of code in your code means, but I see that your VMCS_HOST_CR3 is different from what I've seen from other codes
other people code is   __vmx_vmwrite(VMCS_HOST_CR3, __readcr3());

You alloc a new memory  ，I don't understand why this is done。Can you give me some reference directions?

**Comment by jonomango** [comment]
Yes, those hypervisors are sharing their page-tables with the guest, which is a bad idea. Sharing any state with the guest is bad in general since it gives them control over your hypervisor. For example, page-table trashing is only possible if you share the same page-tables as the guest... it is better to make your own.
