### ISSUE TITLE
BSOD on 21H1

### ISSUE THREAD

**Issue by OmhaRobin1** [jonomango/hv#5]
Hey, when manual mapping the hypervisor i bluescreen with code CLOCK_WATCHDOG_TIMEOUT upon calling vm_launch. 

Only modifications ive made are launching the hypervisor from a system thread, system specs + info are below

Windows version: 21H1 Pro (OS Build 19043.1889)
Processor: Intel i9-10850k
Virtualization: Enabled
Hyper-V: Disabled

**Comment by jonomango** [comment]
Hi, can you test the hypervisor as-is without modifying the repo? Loading the driver normally without manual mapping would also help a lot (just use Windows Test Mode). If the hypervisor still causes a BSOD, please send the crash dump. Otherwise, the issue is probably due to manual mapping, or how you're launching it from your system thread.

**Comment by OmhaRobin1** [comment]
Hey, yeah i tested it unmodified aswell and it was the exact same issue, ill upload a crash dump shortly. works fine in a vm but not outside one

**Comment by jonomango** [comment]
Closed due to inactivity.
