### ISSUE TITLE
seek help : Questions about the host_physical_memory_base

### ISSUE THREAD

**Issue by GitHubHengheng** [jonomango/hv#55]
Hello, PEPT_PTE pt = (host_physical_memory_base + (ept->pds[addr.pdpt_idx][addr.pd_idx].page_frame_number << 12));
What is the principle of host_physical_memory_base? I have read the materials, but I still can't understand it. I do not know if I can spare time, simple explanation west, most of the rest of the writing and principles have been understood.

1:25 <<(9+9+9+9+12) = 7F80 '00000000
What we get here is why can this number be a physical base?

**Comment by jonomango** [comment]
Essentially, I have mapped most of physical memory into the host page tables: https://github.com/jonomango/hv/blob/main/hv/page-tables.cpp#L9. Physical address `0x0` is mapped to `host_physical_memory_base` and physical address `0x1000` is mapped to `host_physical_memory_base + 0x1000` and so on. The 12 comes from the number of bits in a page offset, the 9 comes from the number of bits for the index for each level of the page tables (PT, PD, PDPT) and `host_physical_memory_pml4_idx` is an arbitrary PML4e index that I have chosen (also 9 bits). This is where the `9 + 9 + 9 + 9 + 12` comes from, since a virtual address is really just a bitfield of page table entry indices + the page offset (https://github.com/jonomango/hv/blob/main/hv/mm.h#L9).
